title: My Website
description: A site styled like LaTeX
baseurl: "" # or your subdirectory
url: "https://tapassahoo.github.io"

theme: minima # or your custom theme
markdown: kramdown

# Optional: Enable Sass/SCSS processing
sass:
  style: compressed
